# Prometheus Configuration for Video Streaming Backend
# Casey - Senior DevOps Engineer
# Performance monitoring for Smart TV optimization

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Streaming backend monitoring
  - job_name: 'streaming-backend'
    static_configs:
      - targets: ['streaming-backend:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Nginx monitoring (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 15s

  # Redis monitoring (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # Node.js application metrics
  - job_name: 'node-app'
    static_configs:
      - targets: ['streaming-backend:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 10s

# Alerting configuration (future enhancement)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093